from PyQt5 import uic
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton
from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class main(QWidget):

    def __init__(self):
        super(main, self).__init__()
        self.setWindowTitle('main')
        self.setMinimumWidth(200)
        self.setMinimumHeight(50)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(70, 10, 251, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 10, 251, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalScrollBar = QtWidgets.QScrollBar(self)
        self.verticalScrollBar.setGeometry(QtCore.QRect(780, 0, 16, 561))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 60, 571, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("main", "MainWindow"))
        self.pushButton.setText(_translate("main", "Виды и свойства информации (Тест 1)"))
        self.pushButton_2.setText(_translate("main", "Виды и свойства информации (Тест 2)"))
        self.pushButton_3.setText(_translate("main", "Информационный объём фрагмента текста"))



class task1(QWidget):
    def __init__(self):
        super(task1, self).__init__()
        self.setWindowTitle('task1')
        self.setMinimumWidth(815)
        self.setMinimumHeight(574)


        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(310, 0, 161, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(340, 100, 211, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(550, 100, 201, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(130, 40, 621, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 321, 31))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(0, 130, 751, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self)
        self.line_2.setGeometry(QtCore.QRect(0, 82, 751, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self)
        self.line_3.setGeometry(QtCore.QRect(320, 100, 31, 331))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self)
        self.line_4.setGeometry(QtCore.QRect(540, 100, 20, 331))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self)
        self.line_5.setGeometry(QtCore.QRect(0, 180, 751, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.checkBox = QtWidgets.QCheckBox(self)
        self.checkBox.setGeometry(QtCore.QRect(440, 160, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self)
        self.checkBox_2.setGeometry(QtCore.QRect(640, 160, 16, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(0, 200, 331, 31))
        self.label_6.setObjectName("label_6")
        self.line_6 = QtWidgets.QFrame(self)
        self.line_6.setGeometry(QtCore.QRect(-3, 220, 751, 41))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self)
        self.checkBox_3.setGeometry(QtCore.QRect(440, 210, 70, 17))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self)
        self.checkBox_4.setGeometry(QtCore.QRect(640, 210, 70, 17))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.line_7 = QtWidgets.QFrame(self)
        self.line_7.setGeometry(QtCore.QRect(0, 300, 751, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(0, 240, 331, 61))
        self.label_7.setObjectName("label_7")
        self.checkBox_5 = QtWidgets.QCheckBox(self)
        self.checkBox_5.setGeometry(QtCore.QRect(440, 270, 70, 17))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self)
        self.checkBox_6.setGeometry(QtCore.QRect(640, 270, 70, 17))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.line_8 = QtWidgets.QFrame(self)
        self.line_8.setGeometry(QtCore.QRect(0, 360, 751, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(6, 312, 321, 61))
        self.label_8.setObjectName("label_8")
        self.checkBox_7 = QtWidgets.QCheckBox(self)
        self.checkBox_7.setGeometry(QtCore.QRect(440, 330, 70, 17))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self)
        self.checkBox_8.setGeometry(QtCore.QRect(640, 330, 70, 17))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.line_9 = QtWidgets.QFrame(self)
        self.line_9.setGeometry(QtCore.QRect(740, 100, 20, 331))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(10, 380, 321, 41))
        self.label_9.setObjectName("label_9")
        self.line_10 = QtWidgets.QFrame(self)
        self.line_10.setGeometry(QtCore.QRect(0, 420, 751, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.checkBox_9 = QtWidgets.QCheckBox(self)
        self.checkBox_9.setGeometry(QtCore.QRect(440, 390, 70, 17))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self)
        self.checkBox_10.setGeometry(QtCore.QRect(640, 390, 70, 17))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 440, 171, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(440, 440, 221, 81))
        self.label_10.setObjectName("label_10")
        self.menubar = QtWidgets.QMenuBar(task1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self)
        self.statusbar = QtWidgets.QStatusBar(task1)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self)

        self.retranslateUi1(task1)
        QtCore.QMetaObject.connectSlotsByName(task1)
        task1.setTabOrder(self.checkBox, self.checkBox_2)
        task1.setTabOrder(self.checkBox_2, self.checkBox_3)
        task1.setTabOrder(self.checkBox_3, self.checkBox_4)
        task1.setTabOrder(self.checkBox_4, self.checkBox_5)
        task1.setTabOrder(self.checkBox_5, self.checkBox_6)
        task1.setTabOrder(self.checkBox_6, self.checkBox_7)
        task1.setTabOrder(self.checkBox_7, self.checkBox_8)
        task1.setTabOrder(self.checkBox_8, self.checkBox_9)
        task1.setTabOrder(self.checkBox_9, self.checkBox_10)


        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow1", "task1"))
        self.label.setText(_translate("MainWindow1", "<html><head/><body><p><span style=\" font-size:18pt;\">Проверь себя!</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Декларативные знания</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Процедурные знания</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Распределите виды знаний в соответствии с их классификацией</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Земля вращается вокруг Солнца</span></p></body></html>"))
        self.checkBox.setToolTip(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Пушкин родился в 1799 году</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Байкал - самое глубокое</span></p><p align=\"center\"><span style=\" font-size:14pt;\"> пресное озеро</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Квадрат гипотенузы равен сумме</span></p><p align=\"center\"><span style=\" font-size:14pt;\"> квадратов катетов</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Как собрать радиоприемник</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow1", "Назад"))
        self.pushButton_2.setText(_translate("MainWindow1", "Ответ"))
        self.label_10.setText(_translate("MainWindow1", "<html><head/><body><p><span style=\" font-size:20pt;\">Верно</span></p></body></html>"))





class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle('MainWindow')
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(70, 10, 251, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText(_translate("MainWindow", "Начать"))

    def show_main(self):
        self.w1 = main()
        self.w1.pushButton.clicked.connect(self.task1)
        self.w1.pushButton.clicked.connect(self.w1.close())
        self.w1.show()

    def show_task1(self):
        self.w2 = task1()
        self.w2.show()
if __name__ == '__main__':

    app = QApplication(sys.argv)

    Pl = MainWindow()
    Pl.show()
    Pl.show_main()


    sys.exit(app.exec_())
